version: "3"

services:
  # FastAPI
  api:
    container_name: "api"
    build: ./api/build/
    restart: always
    tty: true
    ports:
      - 8000:80
    volumes:
      - type: bind
        # source: /mnt/c/Users/Public/GitHub/prac/docker/python_fastapi/api/app
        source: C:\Users\Public\GitHub\prac\docker\python_fastapi\api\app
        target: /app
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 80"


  # PostgreSQL
  db:
    container_name: "db"
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: document_db
      LANG: ja_JP.UTF-8
    # volumes:
    #   - type: bind
    #     source: /mnt/c/Users/Public/GitHub/prac/docker/python_fastapi/db/data
    #     target: /data
    #   - type: bind
    #     source: /mnt/c/Users/Public/GitHub/prac/docker/python_fastapi/db/docker-entrypoint-initdb.d
    #     target: /docker-entrypoint-initdb.d

  # React
  web:
    container_name: "web"
    image: node:15.14.0-buster-slim
    ports:
      - 3000:3000
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
      NODE_ENV: deveropment
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - type: bind
        # source: /mnt/c/Users/Public/GitHub/prac/docker/python_fastapi/web/app
        source: C:\Users\Public\GitHub\prac\docker\python_fastapi\web\app
        target: /app
    command: sh -c "cd /app && yarn start"

